### ISSUE TITLE
error with Jason

### ISSUE THREAD

**Issue by KingSte439** [KingSte439/Jason#1]
JSON CODE

var jcontent = {
    "Vorname": "Steven",
    "Nachname": "S."
}
var output = document.getElementById('output');
output.innerHTML = jcontent.Vorname + '' + jcontent.Nachname;

----------------------------------------------------------------------------------------------------------------
HTML CODE
 <body>
                            
                        <div id="container">
                            <div id="output">Hier steht noch nichts</div>
                            </div>
                            <script src="script.js"></script>
 </body>

**Comment by KingSte439** [comment]
<body>
                            
                        <div id="container">
                            <div id="output">Hier steht noch nichts</div>
                            </div>
                            <script src="script.js"></script>
                        </body>

**Comment by rilleralle** [comment]
```
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Title of the document</title>
</head>

<body>
    <div id="output"></div>
    <script>
        var jcontent = {
            "Vorname": "Steven",
            "Nachname": "S."
        }
        var output = document.getElementById('output');
        output.innerHTML = jcontent.Vorname + '' + jcontent.Nachname;
    </script>
</body>

</html>
```

**Comment by rilleralle** [comment]
HTML
```
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Title of the document</title>
</head>

<body>
    <div id="output"></div>
    <script src="script.js"></script>
</body>

</html>
```
JS
```
var jcontent = {
    "Vorname": "Steven",
    "Nachname": "S."
}
var output = document.getElementById('output');
output.innerHTML = jcontent.Vorname + '' + jcontent.Nachname;
```
